base_uri: 'https://api.openagenda.com/v2/'
endpoints:
  agenda:
    method: GET
    path:  'agendas/{agendaUid}'
    headers:
      accept: 'application/json'
  events:
    method: GET
    path:  'agendas/{agendaUid}/events'
    headers:
      accept: 'application/json'
  event:
    method: GET
    path:  'agendas/{agendaUid}/events/{eventUid}'
    headers:
      accept: 'application/json'
